### ISSUE TITLE
No easy way to join the slack channel

### ISSUE THREAD

**Issue by Darkflib** [lhawthorn/Well-BeinginTechConf#1]
You might want to consider http://rauchg.com/slackin/ as a way to automate sending join requests.

Also, can you add myself mike at technomonk.com as I am certainly interested in assisting.

**Comment by lhawthorn** [comment]
Sorry, I just saw this issue and clearly need to fix my GitHub notifications to filter more effectively. You've been sent an invite.

Checking in with the lovely human coordinating the Slack channel on the automated join request option you've mentioned. Appreciate the suggestion. Will update this issue when this is resolved.

**Comment by ksatirli** [comment]
@Darkflib Slackin is what I was looking for! The way the socket.io team solved this is too beautiful to want to build something myself.

I'll get this set-up over the weekend!
